Add title attribute to anchor tag
Icinga/icingaweb2-module-generictts pull request #14
Opened 2022-08-26 12:29 UTC by raviks789

The title attribute is added to the anchor tag while creating the ticket link to show the url of the link upon hover.

## Before:
![ticket_link_before](https://user-images.githubusercontent.com/33730024/186903565-5b58972b-6991-4dfe-8480-d80dccffdcf6.png)

## After:
![ticket_link_after](https://user-images.githubusercontent.com/33730024/186903579-3b861078-1a75-44bc-a622-84ccaeed9ab9.png)

2022-09-02 08:22 UTC, lippserd requested changes
`sprintf` has support for numbered arguments. Please don't duplicate code.

2022-09-02 12:06 UTC, lippserd approved these changes

2022-11-29 13:08 UTC, nilmerg commented
Just out of curiosity, where does this come from? I mean, look in the bottom right corner of each screenshot. The full URL is shown there in a sufficiently sophisticated browser. (Even in Firefox :joy: ) Why do we need this?

2022-11-29 14:36 UTC, lippserd commented
> Just out of curiosity, where does this come from? I mean, look in the bottom ~right~left corner of each screenshot. The full URL is shown there in a sufficiently sophisticated browser. (Even in Firefox 😂 ) Why do we need this?

😆 True. Since this is an external URL, I found it useful to display it in the current focus. But, of course, we don't necessarily have to include that.

2022-11-29 14:40 UTC, nilmerg commented
To me this is just redundant information. Users should nowadays know that the full URL of a link is shown a the bottom while hovering. This is a important security measure most browsers have and will make sure is displayed.

2022-11-29 15:40 UTC, closed without merging